travis:
  secure:
    BINSTAR_TOKEN: gI5G/9SYz8Lx/9PK+AzAFJjZxgSY2BmVXnuQ1lTM7ZHrGE5IOP72oPg70PQClHr3yaDiQQUeTLZm9Lh909IuOD1++7fgkCJjDnUItxzFq7CoKHS2mbIGDfGSItdQmuRhhJIxvkLHbVeEi/FtMzPREnvaWDetBiyLxr84VTN+PY2LQxMskMirA22DVQck3S8CuYns8ak0WVyfPOJCuOwFpnnEmzFo/A54ii407R9wf6ys+jZFYCTa8kUBWuVUAIbEurgR9fJIPT/lZhSa8w6H9r/CgryLpdUvtQravrzU0BgFvrD1Rbw9CRViHxRAOsg5Wh1mu+Zj1tLwocdZhiKjrjZwZQXyQXPAj4tiV+H4QGL89QeunjCdVfSL6nuS8ybS21Z/OmmSoHMdOTqFLLeRUUFDOtLEcNmBgUUbFRKcEIqCUpuwacchJIVeK9b8UQ64VrQiKp/ScMrrrkhKyQasv6mMnzm8r3m+zBsyZcN5stDjADpc4LEkS0I9nlZCO/94syCYJjc0Vh00+phdfxW0MuxNlIu+KeQpzIVTNTAnuN0/yRLGxJ86x+Urjo4G8yaiuMi6Sq8IgC65O6t+mz/ERUqJ1/ZGW4tW2QhszgHQyGpdGtJ9xbcm/gHpi2SsiwVct5FNzoTYXdXtVdRFGXwKidXSE2fv4bnxc6ReHHSLSw4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
