travis:
  secure:
    BINSTAR_TOKEN: pxO7UJFdq3IwlFxwfbKDd3ISppJfhQJn8IvHysibJNz0c9eGJO4BYZktEMjPzunmfr6TR40RK8UqnVEj64IO7hflLKFR4keobn9lKzWiy57ZTi7CfCFe82bqhVXaVwVYaDMhZvrb4xoe6rbaeIo5n/IHIiVKjICqnR0yWWRwhuPxy7dDgbJn/i2SmMVbgWfTr+tZaEj4qPBIkH65QGlStJWEQhjhzb9CbaqxQ2xj5XywQNPA/4pu0NkyJMII5Sx2hwOoAj/QchXI9wkVyOw3K+akXd5BkKMZuzYr2P79s67xluFvv7x5aRZzH47hWk9y95qBihjv5B5hdEfcrik3unGP3/MSQIFBA4k3Ajh+GDh6q7v731xMfTR1qTtsMdS2lUQC72yTTm3sxpoepP1jvu17yLVGrC+giUIILdMpeSZvwbcuKhsBHKZyBm8Bzb7KfJCgV1ZzwXCbJelj1BQYFaZ1GnBbamNn++CQSWTaXfoDawpzD+txx+jHFEp7+jdJZMl2pAUjBo4NFipZdMhZZDU1XsK8yHCzjWYOvGFGBgK3ZYi4GzStoe22jzSFP7/SZPsHUdP4N0z0ft4OnvfGOBdP1AVdTE/yGJa/vuLwIMDfqZ5D8B5ln4Bk+yG9weNUOSyQce7xVaHRiRvyoYaq3/3NKG9MxyR5mTnhNvQlUw8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
